
import { AppSettings, BrewMethod, Language } from './types';

export const DEFAULT_SETTINGS: AppSettings = {
  language: 'zh',
  caffeineHalfLife: 5,
  safeSleepThreshold: 50,
  dailyLimit: 400,
  brewRatio: 15,
  tempUnit: 'c',
  theme: 'system',
  defaultReviewMode: 'barista',
};

export const BREW_METHODS: Record<BrewMethod, { caffeineFactor: number; label: Record<Language, string>; defaultDose: number }> = {
  pour_over: { caffeineFactor: 120, label: { en: 'Pour Over', zh: '手冲', ja: 'ハンドドリップ' }, defaultDose: 15 },
  espresso: { caffeineFactor: 65, label: { en: 'Espresso', zh: '意式浓缩', ja: 'エスプレッソ' }, defaultDose: 18 },
  aeropress: { caffeineFactor: 100, label: { en: 'Aeropress', zh: '爱乐压', ja: 'エアロプレス' }, defaultDose: 15 },
  french_press: { caffeineFactor: 150, label: { en: 'French Press', zh: '法压壶', ja: 'フレンチプレス' }, defaultDose: 20 },
  cold_brew: { caffeineFactor: 200, label: { en: 'Cold Brew', zh: '冷萃', ja: '水出し' }, defaultDose: 40 },
  moka: { caffeineFactor: 90, label: { en: 'Moka Pot', zh: '摩卡壶', ja: 'マキネッタ' }, defaultDose: 15 },
  other: { caffeineFactor: 100, label: { en: 'Other', zh: '其他', ja: 'その他' }, defaultDose: 15 },
};

export const PRESET_BRANDS: Record<string, Record<Language, string>> = {
  'Starbucks': { en: 'Starbucks', zh: '星巴克', ja: 'スターバックス' },
  'Luckin': { en: 'Luckin Coffee', zh: '瑞幸咖啡', ja: 'ラッキンコーヒー' },
  'McCafé': { en: 'McCafé', zh: '麦咖啡', ja: 'マックカフェ' },
  'K-Coffee': { en: 'K-Coffee', zh: '肯悦咖啡', ja: 'ケンタッキー' },
  'Cotti': { en: 'Cotti Coffee', zh: '库迪咖啡', ja: 'コッティコーヒー' },
  'Blue Bottle': { en: 'Blue Bottle', zh: '蓝瓶咖啡', ja: 'ブルーボトル' },
  'Costa': { en: 'Costa', zh: '咖世家', ja: 'コスタ' },
  'Tim Hortons': { en: 'Tim Hortons', zh: 'Tims天好', ja: 'ティムホートンズ' },
  '% Arabica': { en: '% Arabica', zh: '% Arabica', ja: '% Arabica' },
};

export const PRESET_BRAND_KEYS: string[] = Object.keys(PRESET_BRANDS);

export const FLAVOR_TAGS = ['Fruity', 'Floral', 'Nutty', 'Cocoa', 'Spicy', 'Herbal', 'Roasted', 'Fermented', 'Sweet', 'Citrus', 'Berry', 'Stone Fruit'];

export const DICTIONARY = {
  en: {
    dashboard: 'Dashboard',
    addLog: 'Add',
    inventory: 'Beans',
    settings: 'Settings',
    currentLevel: 'Caffeine Level',
    todayTotal: 'Today',
    mg: 'mg',
    halfLife: 'Half-life',
    hours: 'hrs',
    exportData: 'Export Data (JSON)',
    importData: 'Import Data (JSON)',
    store: 'Store Bought',
    homemade: 'Homemade',
    brand: 'Brand',
    product: 'Product',
    bean: 'Coffee Bean',
    method: 'Method',
    caffeineEst: 'Est. Caffeine',
    add: 'Add',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    activeBeans: 'Inventory',
    history: 'History',
    noLogs: 'No coffee records found.',
    sleepWarning: 'High caffeine!',
    metabolismChart: 'Metabolism',
    customBrand: 'Custom Brand',
    roast: 'Roast',
    process: 'Process',
    beanName: 'Bean Name',
    light: 'Light',
    medium: 'Medium',
    dark: 'Dark',
    washed: 'Washed',
    natural: 'Natural',
    honey: 'Honey',
    anaerobic: 'Anaerobic',
    other: 'Other',
    finished: 'Finished',
    reopen: 'Active',
    selectBean: 'Select bean...',
    newBrand: 'New Brand',
    enterBrandName: 'Brand name',
    selectBrand: 'Select brand...',
    calendar: 'Calendar',
    searchPlaceholder: 'Search coffee...',
    allHistory: 'All History',
    clearDate: 'Clear Date',
    weight: 'Weight',
    grams: 'g',
    addNewBean: 'Add New Bean',
    totalBeans: 'Total Bags',
    activeCount: 'Active',
    beanInventory: 'Bean Inventory',
    dailyLimit: 'Daily Limit',
    preferences: 'Preferences',
    appearance: 'Appearance',
    brewRatio: 'Default Brew Ratio',
    tempUnit: 'Temp Unit',
    theme: 'Theme',
    system: 'System',
    general: 'General',
    health: 'Health',
    brewing: 'Brewing',
    data: 'Data',
    dose: 'Dose (g)',
    remaining: 'Remaining',
    date: 'Time',
    aiGuide: 'AI Brew Guide',
    generating: 'Brewing recipe...',
    aiError: 'Failed to generate recipe.',
    review: 'Review',
    editReview: 'Edit Review',
    rebuy: 'Rebuy?',
    notes: 'Notes',
    casual: 'Casual',
    barista: 'Barista',
    expert: 'Expert',
    acidity: 'Acidity',
    sweetness: 'Sweetness',
    body: 'Body',
    bitterness: 'Bitterness',
    aftertaste: 'Aftertaste',
    aroma: 'Aroma',
    balance: 'Balance',
    uniformity: 'Uniformity',
    cleanCup: 'Clean Cup',
    overall: 'Overall',
    totalScore: 'Total Score',
    flavors: 'Flavors',
    defaultReviewMode: 'Default Review Mode',
    noReview: 'No review yet',
    deleteConfirm: 'Delete this record?',
    deleteBeanConfirm: 'Delete this bean?',
    importConfirm: 'Found {logs} new logs and {beans} new beans.\nMerge them into your current data?',
    importSuccess: 'Successfully imported data!',
    invalidFile: 'Invalid JSON file.',
  },
  zh: {
    dashboard: '概览',
    addLog: '记录',
    inventory: '豆仓',
    settings: '设置',
    currentLevel: '当前残留',
    todayTotal: '今日',
    mg: '毫克',
    halfLife: '半衰期',
    hours: '小时',
    exportData: '导出数据 (JSON)',
    importData: '导入数据 (JSON)',
    store: '外购',
    homemade: '自制',
    brand: '品牌',
    product: '商品',
    bean: '豆子',
    method: '方式',
    caffeineEst: '预估含量',
    add: '添加',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    activeBeans: '库存管理',
    history: '历史记录',
    noLogs: '没有找到记录。',
    sleepWarning: '咖啡因较高！',
    metabolismChart: '代谢趋势',
    customBrand: '自定义',
    roast: '烘焙',
    process: '处理',
    beanName: '名称',
    light: '浅烘',
    medium: '中烘',
    dark: '深烘',
    washed: '水洗',
    natural: '日晒',
    honey: '蜜处理',
    anaerobic: '厌氧',
    other: '其他',
    finished: '已喝完',
    reopen: '喝着呢',
    selectBean: '选择豆子...',
    newBrand: '新品牌',
    enterBrandName: '输入品牌名',
    selectBrand: '选择品牌...',
    calendar: '日历',
    searchPlaceholder: '搜索咖啡记录...',
    allHistory: '全部记录',
    clearDate: '清除日期',
    weight: '重量',
    grams: '克',
    addNewBean: '入库新豆',
    totalBeans: '总库存',
    activeCount: '喝着呢',
    beanInventory: '豆仓管理',
    dailyLimit: '每日上限',
    preferences: '偏好设置',
    appearance: '外观',
    brewRatio: '默认粉液比',
    tempUnit: '温度单位',
    theme: '主题',
    system: '跟随系统',
    general: '通用',
    health: '健康管理',
    brewing: '冲煮参数',
    data: '数据管理',
    dose: '粉重 (g)',
    remaining: '剩余',
    date: '时间',
    aiGuide: 'AI 智能冲煮向导',
    generating: '正在生成配方...',
    aiError: '无法生成配方。',
    review: '评价',
    editReview: '修改评价',
    rebuy: '会回购吗？',
    notes: '笔记',
    casual: '休闲',
    barista: '咖啡师',
    expert: '专家(SCA)',
    acidity: '酸度',
    sweetness: '甜感',
    body: '醇度',
    bitterness: '苦度',
    aftertaste: '余韵',
    aroma: '干/湿香',
    balance: '平衡度',
    uniformity: '一致性',
    cleanCup: '干净度',
    overall: '综评',
    totalScore: '总分',
    flavors: '风味标签',
    defaultReviewMode: '默认评价模式',
    noReview: '暂无评价',
    deleteConfirm: '确认删除这条记录吗？',
    deleteBeanConfirm: '确认删除这支豆子吗？',
    importConfirm: '发现了 {logs} 条新记录和 {beans} 款新豆子。\n确认将它们合并到当前数据中吗？',
    importSuccess: '导入成功！',
    invalidFile: '无效的 JSON 文件。',
  },
  ja: {
    dashboard: 'ホーム',
    addLog: '記録',
    inventory: '豆リスト',
    settings: '設定',
    currentLevel: '現在量',
    todayTotal: '本日',
    mg: 'mg',
    halfLife: '半減期',
    hours: '時間',
    exportData: '出力 (JSON)',
    importData: '入力 (JSON)',
    store: 'お店',
    homemade: '自宅',
    brand: 'ブランド',
    product: '商品',
    bean: '豆',
    method: '淹れ方',
    caffeineEst: '目安量',
    add: '追加',
    cancel: 'キャンセル',
    save: '保存',
    delete: '削除',
    activeBeans: '在庫管理',
    history: '履歴',
    noLogs: '記録が見つかりません。',
    sleepWarning: 'カフェイン高め！',
    metabolismChart: '代謝予測',
    customBrand: 'カスタム',
    roast: '焙煎',
    process: '精製',
    beanName: '豆名',
    light: '浅煎り',
    medium: '中煎り',
    dark: '深煎り',
    washed: '水洗',
    natural: '日晒',
    honey: 'ハニー',
    anaerobic: '嫌気性',
    other: 'その他',
    finished: '完飲',
    reopen: '在庫あり',
    selectBean: '豆を選択...',
    newBrand: '新ブランド',
    enterBrandName: 'ブランド名',
    selectBrand: 'ブランド選択...',
    calendar: 'カレンダー',
    searchPlaceholder: '検索...',
    allHistory: '全履歴',
    clearDate: '日付解除',
    weight: '重量',
    grams: 'g',
    addNewBean: '新しい豆を追加',
    totalBeans: '総在庫',
    activeCount: '使用中',
    beanInventory: 'コーヒー豆在庫',
    dailyLimit: '1日摂取上限',
    preferences: '環境設定',
    appearance: '外観',
    brewRatio: '抽出比率',
    tempUnit: '温度単位',
    theme: 'テーマ',
    system: 'システム',
    general: '一般',
    health: '健康管理',
    brewing: '抽出設定',
    data: 'データ管理',
    dose: '使用量 (g)',
    remaining: '残り',
    date: '日時',
    aiGuide: 'AI 抽出ガイド',
    generating: 'レシピ作成中...',
    aiError: '生成に失敗しました。',
    review: 'レビュー',
    editReview: 'レビュー編集',
    rebuy: 'リピートする？',
    notes: 'メモ',
    casual: 'カジュアル',
    barista: 'バリスタ',
    expert: 'エキスパート',
    acidity: '酸味',
    sweetness: '甘み',
    body: 'コク',
    bitterness: '苦味',
    aftertaste: '後味',
    aroma: '香り',
    balance: 'バランス',
    uniformity: '均一性',
    cleanCup: 'クリーン',
    overall: '総合評価',
    totalScore: '総合点',
    flavors: 'フレーバー',
    defaultReviewMode: 'デフォルト評価モード',
    noReview: 'レビューなし',
    deleteConfirm: 'この記録を削除しますか？',
    deleteBeanConfirm: 'この豆を削除しますか？',
    importConfirm: '{logs}件の新しい記録と{beans}個の新しい豆が見つかりました。\nこれらを現在のデータに統合しますか？',
    importSuccess: 'インポート完了！',
    invalidFile: '無効なJSONファイルです。',
  },
};
